language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - npm run test
# after_script: "istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
after_success: npm run coverage
